export const USER_SIGN_IN_SUCCESS='USER_SIGN_IN';
export const USER_SIGN_IN_ERROR='USER_SIGN_ERROR';
export const USER_LOGOUT_SUCCESS='USER_LOGOUT_SUCCESS';
export const GET_USER_INFO_REQUEST='GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESS='GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILED='GET_USER_INFO_FAILED';
export const EL='EL';